create extension if not exists btree_gist;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  phone text,
  gender text check (gender in ('male', 'female')),
  photo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cities (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  photo_url text,
  created_at timestamptz not null default now()
);

create table public.court_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.courts (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities(id) on delete restrict,
  category_id bigint references public.court_categories(id) on delete set null,
  name text not null,
  thumbnail_url text,
  about text,
  material text not null,
  price_per_hour integer not null check (price_per_hour >= 0),
  address text not null,
  phone text,
  status text not null default 'active' check (status in ('active', 'inactive', 'maintenance')),
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.court_images (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0
);

create table public.court_features (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  name text not null
);

create table public.court_operating_hours (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  day_of_week integer not null check (day_of_week between 0 and 6),
  open_hour integer not null check (open_hour between 0 and 23),
  close_hour integer not null check (close_hour between 1 and 24),
  unique (court_id, day_of_week),
  check (open_hour < close_hour)
);

create table public.court_blocked_slots (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  blocked_date date not null,
  start_hour integer not null check (start_hour between 0 and 23),
  end_hour integer not null check (end_hour between 1 and 24),
  reason text,
  check (start_hour < end_hour)
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  court_id bigint not null references public.courts(id) on delete restrict,
  booking_date date not null,
  start_hour integer not null check (start_hour between 0 and 23),
  end_hour integer not null check (end_hour between 1 and 24),
  total_hours integer generated always as (end_hour - start_hour) stored,
  price_per_hour integer not null check (price_per_hour >= 0),
  sub_total integer generated always as ((end_hour - start_hour) * price_per_hour) stored,
  tax_amount integer not null default 0 check (tax_amount >= 0),
  grand_total integer generated always as (((end_hour - start_hour) * price_per_hour) + tax_amount) stored,
  status text not null default 'pending_payment' check (status in ('pending_payment', 'paid', 'cancelled', 'expired', 'failed')),
  expires_at timestamptz,
  time_range int4range generated always as (int4range(start_hour, end_hour, '[)')) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (start_hour < end_hour),
  exclude using gist (
    court_id with =,
    booking_date with =,
    time_range with &&
  ) where (status in ('pending_payment', 'paid'))
);

create table public.payments (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'midtrans',
  provider_order_id text unique,
  snap_token text,
  redirect_url text,
  amount integer not null check (amount >= 0),
  status text not null default 'pending' check (status in ('pending', 'settlement', 'capture', 'deny', 'cancel', 'expire', 'failure')),
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_courts_updated_at
before update on public.courts
for each row execute function public.set_updated_at();

create trigger set_bookings_updated_at
before update on public.bookings
for each row execute function public.set_updated_at();

create trigger set_payments_updated_at
before update on public.payments
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, phone, gender, photo_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    new.raw_user_meta_data->>'phone',
    nullif(new.raw_user_meta_data->>'gender', ''),
    new.raw_user_meta_data->>'photo_url'
  )
  on conflict (id) do update set
    name = excluded.name,
    email = excluded.email,
    phone = excluded.phone,
    gender = excluded.gender,
    photo_url = coalesce(excluded.photo_url, public.profiles.photo_url),
    updated_at = now();

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.format_rupiah(amount integer)
returns text
language sql
stable
as $$
  select 'Rp ' || replace(to_char(amount, 'FM999,999,999,999'), ',', '.');
$$;

create or replace function public.court_to_json(c public.courts)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'id', c.id,
    'name', c.name,
    'thumbnail', c.thumbnail_url,
    'photos', coalesce((select jsonb_agg(ci.image_url order by ci.sort_order, ci.id) from public.court_images ci where ci.court_id = c.id), '[]'::jsonb),
    'about', c.about,
    'features', coalesce((select jsonb_agg(cf.name order by cf.id) from public.court_features cf where cf.court_id = c.id), '[]'::jsonb),
    'material', c.material,
    'price_per_hour', c.price_per_hour,
    'price_per_hour_formatted', public.format_rupiah(c.price_per_hour),
    'address', c.address,
    'phone', c.phone,
    'status', c.status,
    'bookings_this_month', (
      select count(*)::integer
      from public.bookings b
      where b.court_id = c.id
        and b.status in ('pending_payment', 'paid')
        and date_trunc('month', b.booking_date::timestamp) = date_trunc('month', now())
    ),
    'city', (select jsonb_build_object('id', ct.id, 'name', ct.name) from public.cities ct where ct.id = c.city_id),
    'category', (select jsonb_build_object('id', cc.id, 'name', cc.name) from public.court_categories cc where cc.id = c.category_id)
  );
$$;

create or replace function public.booking_to_json(b public.bookings)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'id', b.id,
    'date', b.booking_date::text,
    'date_formatted', to_char(b.booking_date, 'FMDay, DD Mon YYYY'),
    'start_time', lpad(b.start_hour::text, 2, '0') || ':00',
    'end_time', lpad(b.end_hour::text, 2, '0') || ':00',
    'time_slot', lpad(b.start_hour::text, 2, '0') || ':00 - ' || lpad(b.end_hour::text, 2, '0') || ':00',
    'total_hours', b.total_hours,
    'price_per_hour', b.price_per_hour,
    'sub_total', b.sub_total,
    'tax_amount', b.tax_amount,
    'grand_total', b.grand_total,
    'grand_total_formatted', public.format_rupiah(b.grand_total),
    'status', b.status,
    'court', (
      select jsonb_build_object(
        'id', c.id,
        'name', c.name,
        'thumbnail', c.thumbnail_url,
        'material', c.material,
        'address', c.address,
        'phone', c.phone,
        'city', (select jsonb_build_object('id', ct.id, 'name', ct.name) from public.cities ct where ct.id = c.city_id),
        'category', (select jsonb_build_object('id', cc.id, 'name', cc.name) from public.court_categories cc where cc.id = c.category_id)
      )
      from public.courts c
      where c.id = b.court_id
    ),
    'created_at', b.created_at::text
  );
$$;

create or replace function public.get_available_slots(p_court_id bigint, p_date date)
returns jsonb
language plpgsql
stable
as $$
declare
  court_record public.courts;
  hours_record public.court_operating_hours;
  slots jsonb;
begin
  select * into court_record from public.courts where id = p_court_id and status = 'active';
  if not found then
    raise exception 'Court is not available';
  end if;

  select * into hours_record
  from public.court_operating_hours
  where court_id = p_court_id
    and day_of_week = extract(dow from p_date)::integer;

  if not found then
    return jsonb_build_object(
      'court_id', court_record.id,
      'court_name', court_record.name,
      'date', p_date::text,
      'price_per_hour', court_record.price_per_hour,
      'slots', '[]'::jsonb
    );
  end if;

  select jsonb_agg(
    jsonb_build_object(
      'time', lpad(hour_value::text, 2, '0') || ':00',
      'available', not exists (
        select 1
        from public.bookings b
        where b.court_id = p_court_id
          and b.booking_date = p_date
          and b.status in ('pending_payment', 'paid')
          and int4range(b.start_hour, b.end_hour, '[)') && int4range(hour_value, hour_value + 1, '[)')
      ) and not exists (
        select 1
        from public.court_blocked_slots bs
        where bs.court_id = p_court_id
          and bs.blocked_date = p_date
          and int4range(bs.start_hour, bs.end_hour, '[)') && int4range(hour_value, hour_value + 1, '[)')
      )
    )
    order by hour_value
  ) into slots
  from generate_series(hours_record.open_hour, hours_record.close_hour - 1) as hour_value;

  return jsonb_build_object(
    'court_id', court_record.id,
    'court_name', court_record.name,
    'date', p_date::text,
    'price_per_hour', court_record.price_per_hour,
    'slots', coalesce(slots, '[]'::jsonb)
  );
end;
$$;

create or replace function public.create_booking(
  p_court_id bigint,
  p_date date,
  p_start_hour integer,
  p_end_hour integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  court_record public.courts;
  booking_record public.bookings;
  expires_at_value timestamptz := now() + interval '15 minutes';
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_start_hour >= p_end_hour then
    raise exception 'Invalid time range';
  end if;

  select * into court_record from public.courts where id = p_court_id and status = 'active';
  if not found then
    raise exception 'Court is not available';
  end if;

  insert into public.bookings (
    user_id,
    court_id,
    booking_date,
    start_hour,
    end_hour,
    price_per_hour,
    tax_amount,
    status,
    expires_at
  )
  values (
    current_user_id,
    p_court_id,
    p_date,
    p_start_hour,
    p_end_hour,
    court_record.price_per_hour,
    0,
    'pending_payment',
    expires_at_value
  )
  returning * into booking_record;

  return jsonb_build_object(
    'booking', public.booking_to_json(booking_record),
    'expires_at', expires_at_value::text,
    'expires_in_seconds', 900
  );
exception
  when exclusion_violation then
    raise exception 'Selected time slot is no longer available';
end;
$$;

alter table public.profiles enable row level security;
alter table public.cities enable row level security;
alter table public.court_categories enable row level security;
alter table public.courts enable row level security;
alter table public.court_images enable row level security;
alter table public.court_features enable row level security;
alter table public.court_operating_hours enable row level security;
alter table public.court_blocked_slots enable row level security;
alter table public.bookings enable row level security;
alter table public.payments enable row level security;

create policy "Users can read own profile" on public.profiles
for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "Public can read cities" on public.cities
for select using (true);

create policy "Public can read categories" on public.court_categories
for select using (true);

create policy "Public can read active courts" on public.courts
for select using (status = 'active');

create policy "Public can read court images" on public.court_images
for select using (true);

create policy "Public can read court features" on public.court_features
for select using (true);

create policy "Public can read operating hours" on public.court_operating_hours
for select using (true);

create policy "Public can read blocked slots" on public.court_blocked_slots
for select using (true);

create policy "Users can read own bookings" on public.bookings
for select using (auth.uid() = user_id);

create policy "Users can cancel own pending bookings" on public.bookings
for update using (auth.uid() = user_id and status = 'pending_payment')
with check (auth.uid() = user_id);

create policy "Users can read own payments" on public.payments
for select using (auth.uid() = user_id);

create policy "Users can insert own payments" on public.payments
for insert with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('payment-proofs', 'payment-proofs', false)
on conflict (id) do update set public = excluded.public;

create policy "Users can upload own profile photo" on storage.objects
for insert with check (
  bucket_id = 'profile-photos'
  and auth.uid()::text = (storage.foldername(name))[1]
);

create policy "Users can update own profile photo" on storage.objects
for update using (
  bucket_id = 'profile-photos'
  and auth.uid()::text = (storage.foldername(name))[1]
) with check (
  bucket_id = 'profile-photos'
  and auth.uid()::text = (storage.foldername(name))[1]
);

create policy "Public can read profile photos" on storage.objects
for select using (bucket_id = 'profile-photos');

create policy "Users can upload own payment proofs" on storage.objects
for insert with check (
  bucket_id = 'payment-proofs'
  and auth.uid()::text = (storage.foldername(name))[1]
);

create policy "Users can read own payment proofs" on storage.objects
for select using (
  bucket_id = 'payment-proofs'
  and auth.uid()::text = (storage.foldername(name))[1]
);
