create table public.community_matches (
  id bigint generated by default as identity primary key,
  host_user_id uuid not null references auth.users(id) on delete cascade,
  court_id bigint not null references public.courts(id) on delete restrict,
  booking_id bigint references public.bookings(id) on delete set null,
  match_date date not null,
  start_hour integer not null check (start_hour between 0 and 23),
  end_hour integer not null check (end_hour between 1 and 24),
  player_capacity integer not null default 4 check (player_capacity = 4),
  skill_level text not null check (skill_level in ('beginner', 'intermediate', 'advanced', 'all')),
  notes text,
  status text not null default 'open' check (status in ('open', 'full', 'pending_payment', 'paid', 'cancelled', 'completed', 'needs_reschedule', 'expired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (start_hour < end_hour)
);

create table public.match_participants (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.community_matches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'player' check (role in ('host', 'player')),
  status text not null default 'joined' check (status in ('joined', 'left', 'cancelled')),
  joined_at timestamptz not null default now(),
  unique (match_id, user_id)
);

create table public.split_bills (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.community_matches(id) on delete cascade,
  participant_id bigint not null references public.match_participants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  payment_id bigint references public.payments(id) on delete set null,
  amount integer not null check (amount >= 0),
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'expired', 'cancelled')),
  proof_path text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, user_id)
);

create trigger set_community_matches_updated_at
before update on public.community_matches
for each row execute function public.set_updated_at();

create trigger set_split_bills_updated_at
before update on public.split_bills
for each row execute function public.set_updated_at();

alter table public.community_matches enable row level security;
alter table public.match_participants enable row level security;
alter table public.split_bills enable row level security;

create policy "Public can read visible community matches" on public.community_matches
for select using (status <> 'cancelled');

create policy "Public can read joined match participants" on public.match_participants
for select using (status = 'joined');

create policy "Users can read own split bills" on public.split_bills
for select using (
  auth.uid() = user_id
  or exists (
    select 1
    from public.community_matches cm
    where cm.id = split_bills.match_id
      and cm.host_user_id = auth.uid()
  )
);

create or replace function public.community_match_to_json(p_match_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with match_row as (
    select cm.*
    from public.community_matches cm
    where cm.id = p_match_id
  ),
  participant_rows as (
    select
      mp.id,
      mp.match_id,
      mp.user_id,
      mp.role,
      mp.status,
      mp.joined_at,
      p.name,
      p.photo_url
    from public.match_participants mp
    left join public.profiles p on p.id = mp.user_id
    where mp.match_id = p_match_id
    order by mp.joined_at, mp.id
  ),
  bill_rows as (
    select
      sb.id,
      sb.match_id,
      sb.participant_id,
      sb.user_id,
      sb.amount,
      public.format_rupiah(sb.amount) as amount_formatted,
      sb.status,
      sb.proof_path,
      sb.paid_at,
      p.name,
      p.photo_url
    from public.split_bills sb
    left join public.profiles p on p.id = sb.user_id
    where sb.match_id = p_match_id
    order by sb.id
  )
  select jsonb_build_object(
    'id', m.id,
    'host_user_id', m.host_user_id,
    'booking_id', m.booking_id,
    'match_date', m.match_date::text,
    'date_formatted', to_char(m.match_date, 'FMDay, DD Mon YYYY'),
    'start_time', lpad(m.start_hour::text, 2, '0') || ':00',
    'end_time', lpad(m.end_hour::text, 2, '0') || ':00',
    'time_slot', lpad(m.start_hour::text, 2, '0') || ':00 - ' || lpad(m.end_hour::text, 2, '0') || ':00',
    'total_hours', m.end_hour - m.start_hour,
    'player_capacity', m.player_capacity,
    'skill_level', m.skill_level,
    'notes', m.notes,
    'status', m.status,
    'created_at', m.created_at::text,
    'participant_count', (
      select count(*)::integer
      from public.match_participants mp
      where mp.match_id = m.id and mp.status = 'joined'
    ),
    'share_amount', coalesce((select min(amount) from public.split_bills sb where sb.match_id = m.id), 0),
    'share_amount_formatted', public.format_rupiah(coalesce((select min(amount) from public.split_bills sb where sb.match_id = m.id), 0)),
    'current_user_participant_id', (
      select mp.id
      from public.match_participants mp
      where mp.match_id = m.id and mp.user_id = auth.uid()
      limit 1
    ),
    'current_user_bill_id', (
      select sb.id
      from public.split_bills sb
      where sb.match_id = m.id and sb.user_id = auth.uid()
      limit 1
    ),
    'current_user_bill_status', (
      select sb.status
      from public.split_bills sb
      where sb.match_id = m.id and sb.user_id = auth.uid()
      limit 1
    ),
    'court', (
      select jsonb_build_object(
        'id', c.id,
        'name', c.name,
        'thumbnail', c.thumbnail_url,
        'material', c.material,
        'price_per_hour', c.price_per_hour,
        'price_per_hour_formatted', public.format_rupiah(c.price_per_hour),
        'address', c.address,
        'phone', c.phone,
        'city', (select jsonb_build_object('id', ct.id, 'name', ct.name) from public.cities ct where ct.id = c.city_id),
        'category', (select jsonb_build_object('id', cc.id, 'name', cc.name) from public.court_categories cc where cc.id = c.category_id)
      )
      from public.courts c
      where c.id = m.court_id
    ),
    'participants', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', pr.id,
          'user_id', pr.user_id,
          'role', pr.role,
          'status', pr.status,
          'joined_at', pr.joined_at::text,
          'name', coalesce(pr.name, 'PadalPro Player'),
          'photo_url', pr.photo_url
        )
      )
      from participant_rows pr
    ), '[]'::jsonb),
    'split_bills', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', br.id,
          'participant_id', br.participant_id,
          'user_id', br.user_id,
          'amount', br.amount,
          'amount_formatted', br.amount_formatted,
          'status', br.status,
          'proof_path', br.proof_path,
          'paid_at', br.paid_at::text,
          'name', coalesce(br.name, 'PadalPro Player'),
          'photo_url', br.photo_url
        )
      )
      from bill_rows br
    ), '[]'::jsonb)
  )
  from match_row m;
$$;

create or replace function public.get_community_matches(
  p_status text default null,
  p_skill_level text default null
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(public.community_match_to_json(cm.id) order by cm.match_date, cm.start_hour, cm.id), '[]'::jsonb)
  from public.community_matches cm
  where cm.status <> 'cancelled'
    and cm.match_date >= current_date
    and (p_status is null or cm.status = p_status)
    and (p_skill_level is null or cm.skill_level = p_skill_level);
$$;

create or replace function public.get_community_match_detail(p_match_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select public.community_match_to_json(p_match_id);
$$;

create or replace function public.create_open_match(
  p_court_id bigint,
  p_match_date date,
  p_start_hour integer,
  p_end_hour integer,
  p_skill_level text,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  match_record public.community_matches;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_start_hour >= p_end_hour then
    raise exception 'Invalid time range';
  end if;

  if p_skill_level not in ('beginner', 'intermediate', 'advanced', 'all') then
    raise exception 'Invalid skill level';
  end if;

  perform 1 from public.courts where id = p_court_id and status = 'active';
  if not found then
    raise exception 'Court is not available';
  end if;

  insert into public.community_matches (
    host_user_id,
    court_id,
    match_date,
    start_hour,
    end_hour,
    skill_level,
    notes
  )
  values (
    current_user_id,
    p_court_id,
    p_match_date,
    p_start_hour,
    p_end_hour,
    p_skill_level,
    nullif(p_notes, '')
  )
  returning * into match_record;

  insert into public.match_participants (match_id, user_id, role)
  values (match_record.id, current_user_id, 'host');

  return public.community_match_to_json(match_record.id);
end;
$$;

create or replace function public.activate_match_booking(p_match_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  match_record public.community_matches;
  court_record public.courts;
  booking_record public.bookings;
  participant_count integer;
  share_amount integer;
  remainder integer;
  participant_record public.match_participants;
  participant_index integer := 0;
begin
  perform public.expire_stale_bookings();

  select * into match_record
  from public.community_matches
  where id = p_match_id
  for update;

  if not found then
    raise exception 'Match not found';
  end if;

  if match_record.booking_id is not null then
    return;
  end if;

  select count(*)::integer into participant_count
  from public.match_participants
  where match_id = p_match_id and status = 'joined';

  if participant_count < match_record.player_capacity then
    return;
  end if;

  select * into court_record
  from public.courts
  where id = match_record.court_id and status = 'active';

  if not found then
    update public.community_matches
    set status = 'needs_reschedule'
    where id = p_match_id;
    return;
  end if;

  begin
    insert into public.bookings (
      user_id,
      court_id,
      booking_date,
      start_hour,
      end_hour,
      price_per_hour,
      tax_amount,
      status,
      expires_at
    )
    values (
      match_record.host_user_id,
      match_record.court_id,
      match_record.match_date,
      match_record.start_hour,
      match_record.end_hour,
      court_record.price_per_hour,
      round(((match_record.end_hour - match_record.start_hour) * court_record.price_per_hour * 0.11)::numeric)::integer,
      'pending_payment',
      now() + interval '15 minutes'
    )
    returning * into booking_record;
  exception
    when exclusion_violation then
      update public.community_matches
      set status = 'needs_reschedule'
      where id = p_match_id;
      return;
  end;

  update public.community_matches
  set booking_id = booking_record.id,
      status = 'pending_payment'
  where id = p_match_id;

  share_amount := booking_record.grand_total / participant_count;
  remainder := booking_record.grand_total - (share_amount * participant_count);

  for participant_record in
    select *
    from public.match_participants
    where match_id = p_match_id and status = 'joined'
    order by joined_at, id
  loop
    participant_index := participant_index + 1;
    insert into public.split_bills (
      match_id,
      participant_id,
      user_id,
      amount,
      status
    )
    values (
      p_match_id,
      participant_record.id,
      participant_record.user_id,
      share_amount + case when participant_index <= remainder then 1 else 0 end,
      'pending'
    )
    on conflict (match_id, user_id) do nothing;
  end loop;
end;
$$;

create or replace function public.join_open_match(p_match_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  match_record public.community_matches;
  participant_count integer;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  perform public.expire_stale_bookings();

  select * into match_record
  from public.community_matches
  where id = p_match_id
  for update;

  if not found then
    raise exception 'Match not found';
  end if;

  if match_record.status not in ('open', 'full') then
    raise exception 'This match is not open for joining';
  end if;

  select count(*)::integer into participant_count
  from public.match_participants
  where match_id = p_match_id and status = 'joined';

  if participant_count >= match_record.player_capacity then
    raise exception 'This match is already full';
  end if;

  insert into public.match_participants (match_id, user_id, role, status)
  values (p_match_id, current_user_id, 'player', 'joined')
  on conflict (match_id, user_id)
  do update set status = 'joined';

  select count(*)::integer into participant_count
  from public.match_participants
  where match_id = p_match_id and status = 'joined';

  if participant_count >= match_record.player_capacity then
    update public.community_matches
    set status = 'full'
    where id = p_match_id and status = 'open';

    perform public.activate_match_booking(p_match_id);
  end if;

  return public.community_match_to_json(p_match_id);
end;
$$;

create or replace function public.confirm_split_bill(
  p_bill_id bigint,
  p_proof_path text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  bill_record public.split_bills;
  match_id_value bigint;
  booking_id_value bigint;
  unpaid_count integer;
  payment_record public.payments;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  perform public.expire_stale_bookings();

  select * into bill_record
  from public.split_bills
  where id = p_bill_id and user_id = current_user_id
  for update;

  if not found then
    raise exception 'Split bill not found';
  end if;

  if bill_record.status <> 'pending' then
    return public.community_match_to_json(bill_record.match_id);
  end if;

  update public.split_bills
  set status = 'paid',
      proof_path = p_proof_path,
      paid_at = now()
  where id = p_bill_id;

  select booking_id into booking_id_value
  from public.community_matches
  where id = bill_record.match_id;

  if booking_id_value is not null then
    insert into public.payments (
      booking_id,
      user_id,
      provider,
      provider_order_id,
      amount,
      status,
      raw_payload
    )
    values (
      booking_id_value,
      current_user_id,
      'manual_split',
      'SPLIT-' || p_bill_id || '-' || extract(epoch from now())::bigint,
      bill_record.amount,
      'settlement',
      jsonb_build_object('proof_path', p_proof_path, 'split_bill_id', p_bill_id)
    )
    returning * into payment_record;

    update public.split_bills
    set payment_id = payment_record.id
    where id = p_bill_id;
  end if;

  select count(*)::integer into unpaid_count
  from public.split_bills
  where match_id = bill_record.match_id
    and status <> 'paid';

  if unpaid_count = 0 then
    select booking_id into booking_id_value
    from public.community_matches
    where id = bill_record.match_id;

    update public.community_matches
    set status = 'paid'
    where id = bill_record.match_id;

    if booking_id_value is not null then
      update public.bookings
      set status = 'paid'
      where id = booking_id_value;
    end if;
  end if;

  return public.community_match_to_json(bill_record.match_id);
end;
$$;

create or replace function public.cancel_community_match(p_match_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  match_record public.community_matches;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select * into match_record
  from public.community_matches
  where id = p_match_id
  for update;

  if not found then
    raise exception 'Match not found';
  end if;

  if match_record.host_user_id <> current_user_id then
    raise exception 'Only host can cancel this match';
  end if;

  update public.community_matches
  set status = 'cancelled'
  where id = p_match_id;

  update public.match_participants
  set status = 'cancelled'
  where match_id = p_match_id and status = 'joined';

  update public.split_bills
  set status = 'cancelled'
  where match_id = p_match_id and status = 'pending';

  if match_record.booking_id is not null then
    update public.bookings
    set status = 'cancelled'
    where id = match_record.booking_id and status = 'pending_payment';
  end if;

  return public.community_match_to_json(p_match_id);
end;
$$;

create or replace function public.expire_stale_bookings()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  expired_count integer;
begin
  update public.bookings
  set
    status = 'expired',
    updated_at = now()
  where status = 'pending_payment'
    and expires_at is not null
    and expires_at <= now();

  get diagnostics expired_count = row_count;

  update public.community_matches cm
  set status = 'expired',
      updated_at = now()
  from public.bookings b
  where cm.booking_id = b.id
    and cm.status = 'pending_payment'
    and b.status = 'expired';

  update public.split_bills sb
  set status = 'expired',
      updated_at = now()
  from public.community_matches cm
  where sb.match_id = cm.id
    and cm.status = 'expired'
    and sb.status = 'pending';

  return expired_count;
end;
$$;
